server:
  port: 9090
  servlet:
    context-path:
    encoding:
            force-response: true
spring:
  application:
    name: demo


# log4j2
logging:
  config: classpath:log4j2.xml

user:
  username: www
  password: www


rocketmq:
  nameServer: 127.0.0.1:9876
  producer:
    group: lvJieTestGroup
